package rs.ac.bg.fon.nprog.server.gui;


import rs.ac.bg.fon.nprog.server.niti.ObradaZahtevaNit;
import rs.ac.bg.fon.nprog.server.niti.PokreniServerNit;

/**
 *
 * @author Nadia
 */
public class FrmServer extends javax.swing.JFrame {
  private PokreniServerNit ps;
    /**
     * Creates new form FrmServer
     */
    public FrmServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPokreni.setText("Pokreni");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setText("Zaustavi");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnPokreni)
                .addGap(33, 33, 33)
                .addComponent(btnZaustavi)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni)
                    .addComponent(btnZaustavi))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ps = new PokreniServerNit(this);
        ps.start();
    }                                          

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {                                            
        ps.zaustaviServer();
    }                                           

    /**
     * @param args the command line arguments
     */
    public void serverJePokrenut() {
        lblPoruka.setText("Server program je pokrenut.");
        btnPokreni.setEnabled(false);
        btnZaustavi.setEnabled(true);
    }

    private void srediFormu() {
        lblPoruka.setEnabled(false);
        serverNijePokrenut();
    }

    public void serverNijePokrenut() {
        lblPoruka.setText("Server program je ugašen.");
        btnPokreni.setEnabled(true);
        btnZaustavi.setEnabled(false);

    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JLabel lblPoruka;
    // End of variables declaration                   
}

